// The share card is a PNG: nothing at runtime can catch it going stale, and
// a stale one is worse than no card at all - the previous version kept
// advertising stats that were 1,500 commits out of date and a client name the
// page had since put under NDA. These tests are the only thing standing
// between an edit to content.ts and a share card that contradicts the site.
//
// They compare source text, not rendered pixels: og-card.html holds the copy
// inline (it's a file:// page - it cannot import content.ts), so the check is
// that every identity string still appears in it verbatim.
//
// Re-run `npm run og` after any change these tests flag.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const card = readFileSync(join(HERE, "og-card.html"), "utf8");
const content = readFileSync(join(HERE, "..", "src", "content.ts"), "utf8");

// Pulls a single-line or wrapped string literal out of the identity object.
// Prettier breaks long values onto the next line, so allow whitespace after
// the colon and rejoin nothing else - each field is one literal.
function identityField(key) {
  const match = content.match(new RegExp(`\\n  ${key}:\\s*\\n?\\s*"([^"]*)"`));
  if (!match) throw new Error(`identity.${key} not found in src/content.ts`);
  return match[1];
}

// The card renders these as HTML, so &, < and > arrive escaped. Nothing in the
// current copy needs it, but a future pitch with an ampersand shouldn't fail
// the test for the wrong reason.
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Long values wrap across lines in the HTML source; compare on collapsed
// whitespace so re-indenting the template is not a test failure.
const collapsedCard = card.replace(/\s+/g, " ");

describe("og-card.html mirrors identity in content.ts", () => {
  for (const key of ["name", "role", "pitch", "location", "availability"]) {
    it(`carries identity.${key} verbatim`, () => {
      const value = escapeHtml(identityField(key)).replace(/\s+/g, " ");
      expect(collapsedCard).toContain(value);
    });
  }
});

describe("og-card.html carries nothing that can go stale", () => {
  // The card is regenerated by hand, so anything in it that changes on a
  // schedule will eventually be wrong. Stats belong in og:description, which
  // vite injects from stats.json on every build.
  it("has no thousands-separated numbers (commit/PR counts)", () => {
    const body = card.slice(card.indexOf("<body"));
    expect(body).not.toMatch(/\d{1,3},\d{3}/);
  });

  it("does not name the stats the hero counters own", () => {
    const body = card.slice(card.indexOf("<body")).toLowerCase();
    for (const word of ["commits", "pull requests", "minted", "protocols"]) {
      expect(body).not.toContain(word);
    }
  });

  // The work entry says "Under NDA, so it stays unnamed here". A card that
  // names the client makes a liar of the page in every link preview.
  it("names no employer the page does not name itself", () => {
    // Comments stripped: they explain the card rather than appearing on it,
    // and their prose would read as unknown proper nouns.
    const body = card
      .slice(card.indexOf("<body"))
      .replace(/<!--[\s\S]*?-->/g, "");
    // Proper-cased words in the card that aren't in the page's own copy at all
    // are the signal - a leftover client name from an older deck.
    const suspects = (body.match(/\b[A-Z][a-zA-Z]{3,}\b/g) ?? []).filter(
      (word) => !content.includes(word),
    );
    expect(suspects, `unknown proper nouns in card: ${suspects.join(", ")}`)
      .toEqual([]);
  });

  it("still declares the size index.html advertises", () => {
    expect(card).toMatch(/width:\s*1200px/);
    expect(card).toMatch(/height:\s*630px/);
  });
});
